version: '3.8'

services:
  ml-service:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    restart: unless-stopped

  mlflow-ui:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/app/mlruns
    command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5001", "--backend-store-uri", "file:///app/mlruns"]
    restart: unless-stopped
