name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run model training
      run: |
        python train_model.py
        
    - name: Test Flask application
      run: |
        python -c "
        from app import app
        with app.test_client() as client:
            response = client.get('/health')
            assert response.status_code == 200
            print('✅ Health check passed')
        "
        
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t flask-ml-service:latest .
    
    - name: Test Docker container
      run: |
        docker run -d -p 5000:5000 --name test-container flask-ml-service:latest
        sleep 30
        curl -f http://localhost:5000/health || exit 1
        docker stop test-container
        echo "✅ Docker container test passed"
